### ISSUE TITLE
Actor age + age at film not working

### ISSUE THREAD

**Issue by jerone** [thomasdstewart/IMDBAge#1]
The actors age is not shown. If I remember correctly, it was shown next to the birthday. Zodiac sign still works.
Also the actors age at the time of the filmography is not working. It shows a negative past time.

Example: https://www.imdb.com/name/nm0343444/?ref_=tt_cl_i2
I expect to see age 65. And for her last credit "Raising Hope", I expect to see "6 years ago while 59 years old, 2012".

Great script!

**Comment by jerone** [comment]
Related: https://greasyfork.org/en/forum/discussion/38339/x

**Comment by jerone** [comment]
ping @thomasdstewart

**Comment by nascentt** [comment]
@jerone  just want to say thanks for forking his code, your version works perfectly!

**Comment by thomasdstewart** [comment]
Thanks @jerone   and @nascentt  for the report and thank you for your patience. This is now fixed in version 2.14.
