### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by arogl** [thomasdstewart/IMDBAge#2]
The following icon is missing as part of this script:

[IMDBAge icon](http://www.stewarts.org.uk/tomsweb/IMDBAge?action=AttachFile&do=get&target=icon.png)

**Comment by jerone** [comment]
It's fixed in my fork: [jerone/IMDBAge](https://github.com/jerone/IMDBAge)

Hopefully @thomasdstewart one day will merge my fork back into this repo.

**Comment by thomasdstewart** [comment]
Thanks @arogl  and @jerone for the report and thank you for your patience. This is now fixed in version 2.14.
